### PR TITLE
Fix: Update the indent rule

### PR DESCRIPTION
**Pull request by stramel**
- 2-space indentation
- VariableDeclarator set to 2 will indent the multi-line variable declarations with 4 spaces
- SwitchCase set to 1 will indent case clauses with 2 spaces with respect to switch statements

Pulled from lighthouse eslintrc file.

### CODE REVIEW

**Comment by philipwalton** [comment]
What's missing from this is the Google style suggestion to indent 4 spaces for line continuations. AFAIK there's no config that supports this currently in this rule, and I wouldn't want to turn on something that reports an error for code that is valid according to the Google style guide.

For example, this is valid:

```js
methodWithAReallyReallyLongNameThatTakesMultipleParams('foo', 'bar',
    function() { // indent 4 spaces to show that this is a continuation.
  doSomething(); // indend 2 spaces as normal within a block.
});
```

**Comment by stramel** [comment]
@philipwalton Is that the suggested spacing on a function inlined into the call expression? Or should it be like this?

```
methodWithAReallyReallyLongNameThatTakesMultipleParams('foo', 'bar',
    function() { // indent 4 spaces to show that this is a continuation.
      doSomething(); // indend 2 spaces as normal within a block. (6 total spaces)
    }); // indent 4 spaces 
```

**Comment by philipwalton** [comment]
Both your example and my example are correct, and I don't think there's a config that supports both.

I'm not able to test it right now, but if there's a config that *doesn't* report errors or warnings for these, then I think it's ok. If it *does* report warnings then I wouldn't want to merge.

**Comment by stramel** [comment]
Alright, well, I believe this will throw warnings. I will close until I can find a solution that better fits all cases. Thanks for your help!

**Pull request closed without merging**
